"""Gameplay, turn rendering, and browser interaction messages."""

MESSAGES: dict[str, tuple[str, str]] = {
    "game.page.title": ("游戏 - one_person_dnd", "Play - one_person_dnd"),
    "game.page.heading": ("游玩", "Play"),
    "game.composer.kicker": ("玩家回合", "Player turn"),
    "game.composer.title": ("下一步行动", "Next action"),
    "game.composer.mark": ("行动", "Action"),
    "game.composer.latest_choices": ("DM 留下的行动灵感", "Ideas from the DM"),
    "game.composer.latest_choices_help": ("左右浏览 · 点击只填入，你仍可修改", "Scroll horizontally · Click to fill, then edit freely"),
    "game.composer.action_label": ("下一步行动", "Next action"),
    "game.composer.action_placeholder": ("描述你的行动…", "Describe your action…"),
    "game.composer.disconnected": ("DM 尚未连接", "DM is not connected"),
    "game.composer.configure_before": ("先到", "Go to"),
    "game.composer.models": ("模型", "Models"),
    "game.composer.configure_after": ("页面保存并启用一个可用配置，再开始行动。", "to save and enable a working profile before taking an action."),
    "game.composer.configure": ("去配置模型", "Configure a model"),
    "game.starter.aria": ("开场行动", "Opening actions"),
    "game.starter.label": ("开场行动", "Opening actions"),
    "game.starter.observe": ("观察四周", "Look around"),
    "game.starter.inventory": ("检查随身物品", "Check your belongings"),
    "game.starter.talk": ("和最近的人交谈", "Talk to the nearest person"),
    "game.composer.send": ("发送", "Send"),
    "game.composer.sending": ("发送中…", "Sending…"),
    "game.composer.cancel": ("取消", "Cancel"),
    "game.composer.thinking": ("DM 思考中…", "DM is thinking…"),
    "game.composer.shortcut": ("发送", "Send"),
    "game.advanced.title": ("高级选项", "Advanced options"),
    "game.advanced.tags_label": ("参考标签（帮助 DM 找到相关世界设定，逗号分隔）", "Reference tags (help the DM find relevant world lore; comma-separated)"),
    "game.advanced.tags_placeholder": ("酒馆,盗贼公会,某个角色", "tavern,thieves guild,a character"),
    "game.advanced.context_label": ("本回合额外线索（可选，只影响这次行动）", "Extra context for this turn (optional; affects only this action)"),
    "game.advanced.context_placeholder": ("例如：我特别留意窗外脚步声，或提醒 DM 上回合的一个细节…", "For example: I listen for footsteps outside, or remind the DM of a detail from last turn…"),
    "game.history.empty": ("（暂无历史，对话从这里开始）", "(No history yet. The conversation starts here.)"),
    "game.history.resize_aria": ("调整故事记录高度", "Resize story history"),
    "game.history.resize_title": ("拖拽调整高度，双击复位", "Drag to resize; double-click to reset"),
    "game.roll.panel_title": ("快速掷骰", "Quick roll"),
    "game.roll.input_aria": ("掷骰表达式", "Dice expression"),
    "game.roll.button": ("掷骰", "Roll"),
    "game.roll.loading": ("掷骰中…", "Rolling…"),
    "game.roll.empty": ("（在此显示掷骰结果）", "(Roll results appear here.)"),
    "game.roll.result_title": ("掷骰结果", "Roll result"),
    "game.roll.context": ("掷骰结果：{expression}", "Roll result: {expression}"),
    "game.roll.use_context": ("带入本回合线索", "Add to this turn's context"),
    "game.session.switch_aria": ("切换章节", "Switch chapter"),
    "game.session.switch": ("切换章节", "Switch chapter"),
    "game.pending.count": ("待确认变更：", "Pending changes:"),
    "game.sidebar.collapse": ("收起冒险面板", "Collapse adventure panel"),
    "game.sidebar.expand": ("展开冒险面板", "Expand adventure panel"),
    "game.layout.reset": ("重置布局", "Reset layout"),
    "game.status.campaign": ("当前冒险", "Current adventure"),
    "game.status.session": ("当前章节", "Current chapter"),
    "game.status.pending": ("待确认变更", "Pending changes"),
    "game.world_setup.aria": ("世界观设置提醒", "World setup reminder"),
    "game.world_setup.title": ("这局还没有世界观", "This adventure has no world lore yet"),
    "game.world_setup.body": ("当前冒险还没有世界设定，当前章节也没有置顶规则。你可以先补几条关键设定，也可以直接空白开局。", "This adventure has no world lore, and this chapter has no pinned rules. Add a few key details, or begin with a blank slate."),
    "game.world_setup.generate": ("生成新冒险", "Generate a new adventure"),
    "game.world_setup.write": ("手动写设定", "Write world lore"),
    "game.world_setup.skip": ("继续空白开局", "Continue without setup"),
    "game.review.aria": ("待审状态和剧情线更新", "Pending state and plot updates"),
    "game.review.title": ("待审状态 / 剧情线更新", "Pending state / plot updates"),
    "game.review.body": ("待确认的 DM 建议：{count} 条。应用前可先查看预览；角色状态和剧情线不会自动改写。", "Pending DM recommendations: {count}. Preview before applying; character state and plot threads never change automatically."),
    "game.review.view": ("查看待审", "Review changes"),
    "game.story.title": ("故事对话", "Story"),
    "game.story.next": ("下一步行动", "Next action"),
    "game.story.jump": ("跳到输入区", "Jump to input"),
    "game.layout.resize_aria": ("调整故事对话和冒险面板宽度", "Resize the story and adventure panels"),
    "game.layout.resize_title": ("拖拽调整宽度，双击复位", "Drag to resize; double-click to reset"),
    "game.sidebar.title": ("冒险面板", "Adventure panel"),
    "game.tabs.aria": ("冒险面板分区", "Adventure panel sections"),
    "game.tabs.character": ("角色", "Character"),
    "game.tabs.world": ("世界", "World"),
    "game.tabs.plot": ("剧情", "Plot"),
    "game.tabs.system": ("系统", "System"),
    "game.character.title": ("角色卡与变更", "Character sheet and changes"),
    "game.character.loading": ("（加载角色卡中…）", "(Loading character sheet…)"),
    "game.world.section": ("场景与世界", "Scene and world"),
    "game.world.scene": ("当前场景", "Current scene"),
    "game.world.scene_placeholder": ("例如：乌鸦酒馆二楼客房", "For example: an upstairs room at the Raven Tavern"),
    "game.world.state": ("临时状态备注（补充角色卡之外的状态）", "Temporary state notes (outside the character sheet)"),
    "game.world.state_placeholder": ("例如：正在潜行、带着诅咒、某个人物正在同行……", "For example: sneaking, cursed, or traveling with someone…"),
    "game.world.pinned": ("置顶世界设定（硬规则 / 重要人物 / 关键地点）", "Pinned world lore (hard rules / key people / key places)"),
    "game.world.pinned_placeholder": ("世界硬规则/重要关系/禁忌…", "World rules / important relationships / taboos…"),
    "game.world.bible_title": ("世界设定", "World lore"),
    "game.world.bible_body": ("当前冒险已保存的世界规则、地点、人物和势力。", "Saved rules, places, people, and factions for this adventure."),
    "game.world.manage": ("管理全部", "Manage all"),
    "game.world.add": ("新增条目", "Add entry"),
    "game.world.empty": ("（暂无世界设定。可以先生成新冒险，或手动新增。）", "(No world lore yet. Generate a new adventure or add an entry manually.)"),
    "game.recall.title": ("本回合参考", "References for this turn"),
    "game.recall.initial": ("（发送一次行动后显示 DM 使用的角色、世界、剧情线、故事记忆、掷骰和行动判定）", "(After an action, this shows the character, world, plot, story memory, rolls, and adjudication used by the DM.)"),
    "game.recall.trimmed": ("已裁剪", "Trimmed"),
    "game.recall.empty": ("（本回合没有可显示的召回上下文；可以尝试填写更具体的标签或状态）", "(No recalled context to show for this turn. Try more specific tags or state details.)"),
    "game.recall.failed": ("（本回合未更新召回信息：DM 调用失败）", "(References were not updated because the DM request failed.)"),
    "game.recall.fallback_title": ("上下文", "Context"),
    "game.recall.fallback_kind": ("上下文", "context"),
    "game.recall.unknown": ("未知", "unknown"),
    "game.recall.tags": ("（{tags}）", "({tags})"),
    "game.recall.preview.session": ("会话：{value}", "Chapter: {value}"),
    "game.recall.preview.scene": ("当前场景：{value}", "Current scene: {value}"),
    "game.recall.preview.name": ("名称：{value}", "Name: {value}"),
    "game.recall.preview.identity": ("种族/职业：{value}", "Ancestry / class: {value}"),
    "game.recall.preview.background": ("背景：{value}", "Background: {value}"),
    "game.recall.preview.goal": ("目标：{value}", "Goal: {value}"),
    "game.recall.preview.hp": ("HP：{value}", "HP: {value}"),
    "game.recall.preview.gold": ("金币：{value}", "Gold: {value}"),
    "game.recall.preview.level": ("等级：{value}", "Level: {value}"),
    "game.recall.preview.inventory": ("物品：{value}", "Inventory: {value}"),
    "game.recall.preview.conditions": ("状态：{value}", "Conditions: {value}"),
    "game.recall.preview.abilities": ("属性：{value}", "Abilities: {value}"),
    "game.recall.preview.skills": ("技能熟练：{value}", "Skill proficiencies: {value}"),
    "game.recall.preview.notes": ("备注：{value}", "Notes: {value}"),
    "game.recall.preview.tags": ("标签：{value}", "Tags: {value}"),
    "game.recall.preview.progress": ("进展：{value}", "Progress: {value}"),
    "game.recall.preview.next": ("下一步：{value}", "Next: {value}"),
    "game.recall.preview.story_scene": ("场景：{value}", "Scene: {value}"),
    "game.recall.preview.story_summary": ("摘要：{value}", "Summary: {value}"),
    "game.recall.preview.unresolved": ("未解决：{value}", "Unresolved: {value}"),
    "game.recall.preview.key_facts": ("要点：{value}", "Key facts: {value}"),
    "game.recall.preview.campaign_summary": ("战役总摘要：{value}", "Campaign summary: {value}"),
    "game.recall.preview.chapter_summary": ("最近章节摘要：{value}", "Recent chapter summary: {value}"),
    "game.recall.preview.check": (
        "{outcome} · {ability_skill} · DC {dc} · 总计 {total}",
        "{outcome} · {ability_skill} · DC {dc} · Total {total}",
    ),
    "game.recall.reason.world_bible": ("匹配玩家填写的标签或置顶世界设定。", "Matched the player's tags or pinned world lore."),
    "game.recall.reason.scene_state": ("注入当前场景和本回合额外上下文。", "Included the current scene and extra context for this turn."),
    "game.recall.reason.character_state": ("注入当前角色状态和角色卡摘要。", "Included the current character state and character sheet summary."),
    "game.recall.reason.dice": ("玩家行动包含掷骰表达式。", "The player's action included a dice expression."),
    "game.recall.reason.cheat_directive": ("当前会话启用了金手指指令。", "A cheat directive is enabled for this chapter."),
    "game.recall.reason.plot_threads": ("注入仍开放的剧情线和下一步。", "Included open plot threads and their next steps."),
    "game.recall.reason.story_memory": ("召回最近剧情记忆和摘要。", "Recalled recent story memories and summaries."),
    "game.recall.reason.action_assessment": ("评估玩家行动类型、风险和掷骰需求。", "Assessed the action type, risks, and need for a roll."),
    "game.recall.reason.budget_trimmed": ("因上下文预算裁剪，未注入本回合 prompt。", "Trimmed by the context budget and not included in this turn's prompt."),
    "game.recall.reason.default": ("作为本回合上下文的一部分注入。", "Included as part of this turn's context."),
    "game.save.button": ("保存", "Save"),
    "game.save.loading": ("保存中…", "Saving…"),
    "game.save.done": ("已保存", "Saved"),
    "game.threads.current": ("当前剧情线", "Current plot threads"),
    "game.threads.next": ("下一步：{next_step}", "Next: {next_step}"),
    "game.threads.empty": ("（暂无进行中的剧情线）", "(No active plot threads.)"),
    "game.threads.section": ("剧情与章节", "Plot and chapter"),
    "game.threads.campaign": ("冒险", "Adventure"),
    "game.threads.session": ("章节", "Chapter"),
    "game.threads.named": ("{id}（{name}）", "{id} ({name})"),
    "game.threads.link": ("剧情线", "Plot threads"),
    "game.threads.manage": ("管理冒险", "Manage adventures"),
    "game.diagnostics.title": ("回合诊断", "Turn diagnostics"),
    "game.diagnostics.body": ("可玩性与协议检查集中在这里，不打断故事阅读。", "Playability and protocol checks stay here without interrupting the story."),
    "game.diagnostics.empty": ("目前没有需要查看的诊断。", "There are no diagnostics to review."),
    "game.system.tools": ("系统与高级工具", "System and advanced tools"),
    "game.system.cheat_enable": ("启用金手指系统提示词", "Enable the cheat system prompt"),
    "game.system.cheat_label": ("系统提示词（仅当前章节生效）", "System prompt (current chapter only)"),
    "game.system.cheat_placeholder": ("例如：允许玩家在剧情关键节点触发一次‘命运改写’，并优先提供非致死解法。", "For example: let the player rewrite fate once at a key story moment, and favor non-lethal solutions."),
    "game.system.cheat_save": ("保存金手指设置", "Save cheat settings"),
    "game.turn.you": ("你", "You"),
    "game.turn.system_judgment": ("系统判定", "System adjudication"),
    "game.turn.action": ("行动：{action}", "Action: {action}"),
    "game.turn.success": ("成功", "Success"),
    "game.turn.failure": ("失败", "Failure"),
    "game.turn.roll_formula": ("d20 [{faces}] 取 {selected}；{ability} 属性修正，{proficiency} 熟练加值，{circumstance} 情境修正 = {total}", "d20 [{faces}], take {selected}; {ability} ability modifier, {proficiency} proficiency bonus, {circumstance} circumstance modifier = {total}"),
    "game.turn.advantage": ("优势", "Advantage"),
    "game.turn.disadvantage": ("劣势", "Disadvantage"),
    "game.turn.natural_20": ("自然 20", "Natural 20"),
    "game.turn.natural_1": ("自然 1", "Natural 1"),
    "game.turn.intent": ("意图：{intent}", "Intent: {intent}"),
    "game.turn.system_roll": ("系统掷骰", "System roll"),
    "game.turn.choice_history": ("当时的行动灵感", "Ideas offered at the time"),
    "game.turn.index": ("回合 {index}", "Turn {index}"),
    "game.turn.latest": ("最新", "Latest"),
    "game.turn.playability_passed": ("可玩性检查通过", "Playability checks passed"),
    "game.turn.dm_notes": ("DM 内部备注", "DM notes"),
    "game.turn.memory_suggestions": ("故事记忆建议", "Story memory suggestions"),
    "game.turn.dm_review": ("DM 审查", "DM review"),
    "game.turn.response_review": ("反应评估", "Response review"),
    "game.error.request_title": ("请求失败", "Request failed"),
    "game.error.request_status": ("请求状态", "Request status"),
    "game.error.unknown": ("未知错误", "Unknown error"),
    "game.error.cancelled_title": ("请求已取消", "Request cancelled"),
    "game.error.cancelled_body": ("行动草稿已保留，可以修改后重新发送。", "Your action draft was kept. Edit it or send it again."),
    "game.error.network": ("网络连接中断，请稍后重试。", "The network connection was interrupted. Try again shortly."),
    "game.error.stream_ended": ("网络连接提前结束，行动草稿已保留，请重试。", "The connection ended early. Your action draft was kept; please retry."),
    "game.error.llm_unconfigured": ("LLM 未配置，请先在 /models 配置。", "No LLM is configured. Configure one at /models first."),
    "game.error.llm_failed": ("DM 调用失败，请检查模型配置或稍后重试。", "The DM request failed. Check the model configuration or try again shortly."),
    "game.error.invalid_action": ("行动数据无效，请检查当前冒险和行动内容后重新发送。", "The action data is invalid. Check the current adventure and action, then send again."),
    "game.error.attempt_conflict": ("这次行动与已保存的尝试发生冲突，请先修改草稿再发送。", "This action conflicts with a saved attempt. Edit the draft before sending it again."),
    "game.error.store_busy": ("本地存档正忙，请稍后使用同一行动重试。", "The local save is busy. Retry the same action shortly."),
    "game.error.store_corrupt": ("这次行动已保存的检定无法读取，请先恢复存档或查看诊断。", "The saved check for this action cannot be read. Restore a save or review diagnostics first."),
    "game.error.turn_failed": ("回合处理失败，请稍后重试。", "Turn processing failed. Try again shortly."),
    "game.error.roll_required": ("请输入掷骰表达式（例如 d20 / 1d20+5 / 2d6-1）", "Enter a dice expression (for example d20 / 1d20+5 / 2d6-1)."),
    "game.error.roll_invalid": ("掷骰表达式无效。请使用 d20、1d20+5 或 2d6-1。", "Invalid dice expression. Use d20, 1d20+5, or 2d6-1."),
    "game.js.scroll_bottom": ("回到底部", "Jump to bottom"),
    "game.js.scroll_unread": ("有新消息 · 回到底部", "New message · Jump to bottom"),
    "game.js.dm_thinking": ("DM 正在思考下一幕…", "DM is preparing the next scene…"),
    "game.js.pending_body": ("待确认的 DM 建议：{count} 条。应用前可先查看预览；角色状态和剧情线不会自动改写。", "Pending DM recommendations: {count}. Preview before applying; character state and plot threads never change automatically."),
    "game.js.choice_filled": ("已填入行动，可直接发送", "Action filled in and ready to send"),
    "game.js.draft_restored": ("已恢复未发送的行动草稿，可继续编辑或发送", "Your unsent action draft was restored. Continue editing or send it."),
    "game.js.context_added": ("已带入本回合线索：{context}", "Added to this turn's context: {context}"),
    "game.js.context_exists": ("该线索已在本回合上下文中", "This detail is already in the turn context"),
    "game.js.context_used": ("已带入过", "Already added"),
    "game.js.context_use": ("已带入线索", "Context added"),
}
