"""Saves, world memory, plot threads, and character-management messages."""

MESSAGES: dict[str, tuple[str, str]] = {
    # Saves and chapters.
    "saves.page_title": ("冒险与章节", "Adventures & Chapters"),
    "saves.eyebrow": ("存档书架", "Save Library"),
    "saves.continue_current": ("继续当前章节", "Continue Current Chapter"),
    "saves.create_full_adventure": ("创建完整新冒险", "Create a Full Adventure"),
    "saves.campaigns.heading": ("全部冒险", "All Adventures"),
    "saves.campaigns.hint": ("选择后，右侧会显示它的章节。", "Select one to show its chapters on the right."),
    "saves.campaign.created_at": ("创建于 {value}", "Created {value}"),
    "saves.campaign.current": ("当前冒险", "Current Adventure"),
    "saves.campaign.view_chapters": ("查看章节", "View Chapters"),
    "saves.campaign.enter": ("进入冒险", "Enter Adventure"),
    "saves.technical_info": ("技术信息", "Technical Information"),
    "saves.campaign.id": ("冒险编号：{id}", "Adventure ID: {id}"),
    "saves.campaigns.empty": (
        "还没有冒险。用“创建完整新冒险”开始第一段旅程。",
        "No adventures yet. Create a full adventure to begin your first journey.",
    ),
    "saves.campaign.create_blank_summary": ("只创建一个空白冒险", "Create a Blank Adventure Only"),
    "saves.campaign.name": ("冒险名称", "Adventure Name"),
    "saves.campaign.name_placeholder": ("例如：乌鸦港疑云", "For example: The Ravenport Mystery"),
    "saves.campaign.create_blank": ("创建空白冒险", "Create Blank Adventure"),
    "saves.chapters.heading": ("当前冒险的章节", "Chapters in the Current Adventure"),
    "saves.chapters.hint": (
        "章节保存独立的故事进度、角色状态与快照。",
        "Each chapter keeps its own story progress, character state, and snapshots.",
    ),
    "saves.chapter.scene_unset": ("场景未设置", "Scene not set"),
    "saves.chapter.current": ("当前章节", "Current Chapter"),
    "saves.chapter.last_played": ("最近游玩 {value}", "Last played {value}"),
    "saves.snapshot.count": ("快照：{count}", "Snapshots: {count}"),
    "saves.chapter.set_current": ("设为当前章节", "Set as Current Chapter"),
    "saves.chapter.enter": ("进入章节", "Enter Chapter"),
    "saves.snapshots.summary": ("快照与故事分支 · {count}", "Snapshots & Story Branches · {count}"),
    "saves.snapshots.safety_note": (
        "恢复快照会把整个会话（场景、角色卡、回合记录、故事记忆、剧情线）都倒回到快照当时的状态；系统会先自动保存当前状态为一份安全快照，误操作后可以再次恢复它撤回。",
        "Restoring a snapshot rewinds the whole session—scene, character sheet, turns, story memory, and plot threads. A safety snapshot is created first so you can undo an accidental restore.",
    ),
    "saves.snapshot.new_name": ("新快照名称", "New Snapshot Name"),
    "saves.snapshot.name_placeholder": ("例如：进入钟楼前", "For example: Before Entering the Bell Tower"),
    "saves.snapshot.save_current": ("保存当前状态", "Save Current State"),
    "saves.snapshot.recent_counts": (
        "本章共 {total} 个快照；下方显示最近 {shown} 个。",
        "Snapshots in this chapter: {total}. Showing the latest {shown}.",
    ),
    "saves.snapshot.turn_meta": ("回合 {index} · {created_at}", "Turn {index} · {created_at}"),
    "saves.snapshot.restore_confirm": (
        "确认恢复到“{name}”吗？这会连同回合记录、故事记忆和剧情线一起倒回到该时间点，之后的内容会被替换；系统会先创建一份恢复前自动备份，可用它撤回。",
        "Restore “{name}”? Turns, story memory, and plot threads will rewind to that point and later content will be replaced. A pre-restore backup will be created first so you can undo this.",
    ),
    "saves.snapshot.restore_here": ("恢复到这里", "Restore Here"),
    "saves.fork.title": ("故事分支标题", "Story Branch Title"),
    "saves.fork.title_placeholder": ("故事分支标题（可选）", "Story branch title (optional)"),
    "saves.fork.create": ("创建故事分支", "Create Story Branch"),
    "saves.snapshots.empty_title": ("本章还没有快照。", "This chapter has no snapshots yet."),
    "saves.snapshots.empty_hint": (
        "为当前状态命名并保存后，就能从这里恢复或创建故事分支。",
        "Name and save the current state, then restore it or branch the story from here.",
    ),
    "saves.chapter.technical": ("章节编号：{id} · 状态：{status}", "Chapter ID: {id} · Status: {status}"),
    "saves.status.active": ("进行中", "Active"),
    "saves.chapters.empty": ("当前冒险还没有章节。", "The current adventure has no chapters yet."),
    "saves.chapter.add_blank_summary": ("添加一个空白章节", "Add a Blank Chapter"),
    "saves.chapter.title": ("章节标题", "Chapter Title"),
    "saves.chapter.title_placeholder": ("例如：第一章·酒馆里的陌生人", "For example: Chapter One · The Stranger at the Inn"),
    "saves.chapter.opening_scene": ("开场场景", "Opening Scene"),
    "saves.chapter.start_scene_placeholder": ("起始", "Beginning"),
    "saves.chapter.create_blank": ("创建空白章节", "Create Blank Chapter"),
    # Plot threads.
    "threads.page_title": ("剧情线", "Plot Threads"),
    "threads.eyebrow": ("追踪未完的事", "Track Unfinished Business"),
    "threads.back_to_play": ("回到游玩", "Back to Play"),
    "threads.open.heading": ("进行中的剧情线", "Active Plot Threads"),
    "threads.open.hint": ("把仍需追查、兑现或选择的事情留在这里。", "Keep unresolved leads, promises, and choices here."),
    "threads.priority_value": ("优先级 {value}", "Priority {value}"),
    "threads.close": ("标记为已结束", "Mark as Closed"),
    "threads.next_step": ("下一步", "Next Step"),
    "threads.edit": ("编辑剧情线", "Edit Plot Thread"),
    "threads.title": ("标题", "Title"),
    "threads.priority": ("优先级", "Priority"),
    "threads.progress": ("当前进展", "Current Progress"),
    "threads.tags": ("标签", "Tags"),
    "threads.save": ("保存修改", "Save Changes"),
    "threads.id": ("剧情线编号：{id}", "Plot Thread ID: {id}"),
    "threads.open.empty": ("目前没有进行中的剧情线。冒险仍然可以自由推进。", "No active plot threads. The adventure can still move forward freely."),
    "threads.add_summary": ("添加一条剧情线", "Add a Plot Thread"),
    "threads.title_placeholder": ("例如：找到失踪的学徒", "For example: Find the Missing Apprentice"),
    "threads.progress_placeholder": ("一句话说明事情进行到哪里……", "Summarize the current progress in one sentence…"),
    "threads.next_placeholder": ("例如：去乌鸦酒馆问老板娘", "For example: Ask the innkeeper at the Raven Inn"),
    "threads.tags_placeholder": ("主线,支线,某个角色", "main,side,a character"),
    "threads.add": ("添加剧情线", "Add Plot Thread"),
    "threads.closed_summary": ("已结束的剧情线（{count}）", "Closed Plot Threads ({count})"),
    "threads.reopen": ("重新开启", "Reopen"),
    "threads.closed.empty": ("还没有已结束的剧情线。", "No closed plot threads yet."),
    "threads.session_technical": ("当前章节技术信息", "Current Chapter Technical Information"),
    "threads.session_id": ("章节编号：{id}", "Chapter ID: {id}"),
    # World Bible and story journal.
    "world.page_title": ("世界设定", "World Bible"),
    "world.current_campaign": ("当前冒险", "Current Adventure"),
    "world.back_to_play": ("回到游玩", "Back to Play"),
    "world.list.heading": ("已经写下的规则、地点、人物与势力", "Recorded Rules, Places, People, and Factions"),
    "world.list.hint": ("DM 会在相关场景中自动参考这些内容。", "The DM automatically refers to these entries in relevant scenes."),
    "world.type.rule": ("规则", "Rule"),
    "world.type.location": ("地点", "Location"),
    "world.type.npc": ("人物", "Character"),
    "world.type.organization": ("势力", "Organization"),
    "world.type.setting": ("设定", "Setting"),
    "world.updated_at": ("更新于 {value}", "Updated {value}"),
    "world.technical_info": ("技术信息", "Technical Information"),
    "world.entry_technical": ("条目编号：{id} · 类型：{type}", "Entry ID: {id} · Type: {type}"),
    "world.empty_title": ("这个世界还是一张白纸。", "This world is still a blank page."),
    "world.empty_hint": ("先写一条最重要的规则、地点或人物，DM 就有了可依循的锚点。", "Write one important rule, place, or character to give the DM an anchor."),
    "world.add_summary": ("添加一条世界设定", "Add a World Entry"),
    "world.add_hint": ("可从地点、人物、势力或硬规则模板开始，也可以自由书写。", "Start from a place, character, faction, or hard-rule template, or write freely."),
    "world.open_editor": ("打开设定编辑器", "Open World Editor"),
    "world.campaign_technical": ("当前冒险技术信息", "Current Adventure Technical Information"),
    "world.campaign_id": ("冒险编号：{id}", "Adventure ID: {id}"),
    "world.new.page_title": ("新建设定", "New World Entry"),
    "world.new.eyebrow": ("给世界增加一个锚点", "Add an Anchor to the World"),
    "world.new.heading": ("添加世界设定", "Add World Entry"),
    "world.new.back": ("返回世界设定", "Back to World Bible"),
    "world.new.tags_hint": ("标签可以写地点名、人物名、势力名或场景关键词，帮助 DM 在需要时找到它。", "Tags can name places, people, factions, or scene keywords so the DM can find this entry when needed."),
    "world.new.type": ("类型", "Type"),
    "world.type.rule_or_taboo": ("规则或禁忌", "Rule or Taboo"),
    "world.type.other": ("其他", "Other"),
    "world.new.title": ("标题", "Title"),
    "world.new.title_placeholder": ("例如：乌鸦酒馆 / 银刃盗贼团 / 维拉牧师", "For example: Raven Inn / Silverblade Guild / Priest Vela"),
    "world.new.tags": ("标签（逗号分隔）", "Tags (comma-separated)"),
    "world.new.tags_placeholder": ("乌鸦酒馆,港口区,线索A", "Raven Inn,harbor district,clue A"),
    "world.new.details_heading": ("填写你关心的细节", "Add the Details You Care About"),
    "world.field.location_geo": ("地理", "Geography"),
    "world.field.location_factions": ("势力", "Factions"),
    "world.field.resources": ("资源", "Resources"),
    "world.field.dangers": ("危险", "Dangers"),
    "world.field.key_locations": ("关键地点", "Key Locations"),
    "world.field.appearance": ("外观", "Appearance"),
    "world.field.motivation": ("动机", "Motivation"),
    "world.field.secret": ("秘密", "Secret"),
    "world.field.relationships": ("关系", "Relationships"),
    "world.field.combat_tendency": ("战斗倾向", "Combat Tendency"),
    "world.field.goal": ("目标", "Goal"),
    "world.field.enemies": ("敌对", "Enemies"),
    "world.field.influence": ("影响范围", "Sphere of Influence"),
    "world.field.hard_constraints": ("硬约束", "Hard Constraints"),
    "world.field.magic_rules": ("魔法规则", "Magic Rules"),
    "world.field.taboos": ("禁忌", "Taboos"),
    "world.new.freeform": ("自由补充（可选）", "Additional Notes (optional)"),
    "world.new.freeform_placeholder": ("任何补充说明……", "Any additional notes…"),
    "world.new.save": ("保存", "Save"),
    "world.new.back_short": ("返回", "Back"),
    "story.page_title": ("剧情摘要", "Story Summaries"),
    "story.heading": ("故事摘要", "Story Summaries"),
    "story.current_chapter": ("当前章节", "Current Chapter"),
    "story.list_heading": ("摘要列表", "Summary List"),
    "story.scene": ("场景", "Scene"),
    "story.summary": ("摘要", "Summary"),
    "story.time": ("时间", "Time"),
    "story.empty": ("还没有摘要（后续会在回合累计后自动生成）。", "No summaries yet. They will be generated as turns accumulate."),
    # Change previews.
    "preview.value.unset": ("未设置", "Not set"),
    "preview.value.none": ("无", "None"),
    "preview.value.empty_object": ("空对象", "empty object"),
    "preview.separator.list": ("、", ", "),
    "preview.separator.fields": ("、", ", "),
    "preview.separator.parts": ("；", "; "),
    "preview.separator.suffix": ("，", ", "),
    "preview.state.name": ("名称：{before} -> {after}", "Name: {before} → {after}"),
    "preview.state.role": ("职业：{before} -> {after}", "Class: {before} → {after}"),
    "preview.state.hp": ("HP：{before} -> {after}", "HP: {before} → {after}"),
    "preview.state.max_hp": ("HP 上限：{before} -> {after}", "Maximum HP: {before} → {after}"),
    "preview.state.gold": ("金币：{before} -> {after}", "Gold: {before} → {after}"),
    "preview.state.inventory": ("物品：{before} -> {after}", "Inventory: {before} → {after}"),
    "preview.state.goal": ("目标：{before} -> {after}", "Goal: {before} → {after}"),
    "preview.state.summary": ("将更新角色状态", "Character state will be updated"),
    "preview.state.invalid_summary": ("无法预览变更", "Unable to preview the character change"),
    "preview.state.invalid_detail": ("变更数据无效。", "The proposed character change is invalid."),
    "preview.state.unrecognized_summary": ("包含未识别字段变更", "Unrecognized character fields will be changed"),
    "preview.state.json_fields": ("JSON 字段：{fields}", "JSON fields: {fields}"),
    "preview.value.clear": ("清空", "Clear"),
    "preview.thread.title": ("标题：{value}", "Title: {value}"),
    "preview.thread.summary_value": ("概要：{value}", "Summary: {value}"),
    "preview.thread.clear_summary": ("清空概要", "Clear summary"),
    "preview.thread.next_step": ("下一步：{value}", "Next step: {value}"),
    "preview.thread.status.open": ("进行中", "Open"),
    "preview.thread.status.closed": ("已关闭", "Closed"),
    "preview.thread.status": ("状态：{value}", "Status: {value}"),
    "preview.thread.priority": ("优先级：{value}", "Priority: {value}"),
    "preview.thread.tags": ("标签：{value}", "Tags: {value}"),
    "preview.thread.update": ("#{id} 更新：{parts}", "#{id} Update: {parts}"),
    "preview.thread.create": ("新建：{title}（{suffix}）", "Create: {title} ({suffix})"),
    "preview.thread.summary": ("将更新剧情线", "Plot threads will be updated"),
    "preview.thread.invalid_summary": ("无法预览剧情线更新", "Unable to preview plot thread updates"),
    "preview.thread.invalid_detail": ("剧情线更新数据无效。", "The proposed plot thread update is invalid."),
    # Character management and save confirmations.
    "character.overview": ("角色概览", "Character Overview"),
    "character.unnamed": ("未命名角色", "Unnamed Character"),
    "character.identity_unset": ("身份未设置", "Identity not set"),
    "character.gold_value": ("金币 {value}", "Gold {value}"),
    "character.summary.goal": ("目标：{value}", "Goal: {value}"),
    "character.summary.inventory": ("物品：{value}", "Inventory: {value}"),
    "character.summary.conditions": ("状态：{value}", "Conditions: {value}"),
    "character.summary.abilities": ("属性：{value}", "Abilities: {value}"),
    "character.summary.notes": ("备注：{value}", "Notes: {value}"),
    "character.list_separator": ("、", ", "),
    "character.ability_separator": ("，", ", "),
    "character.no_sheet": ("（暂无角色卡。可以用新冒险向导生成，或在高级 JSON 中粘贴一份角色卡。）", "No character sheet yet. Generate one with the new-adventure guide or paste one into Advanced JSON."),
    "character.quick_adjust": ("快捷改值", "Quick Adjust"),
    "character.unknown": ("未知", "Unknown"),
    "character.quick_values": ("HP = {hp}，金币 = {gold}", "HP = {hp}, Gold = {gold}"),
    "character.hp_delta": ("HP 增量", "HP Change"),
    "character.gold_delta": ("金币增量", "Gold Change"),
    "character.reason_optional": ("原因（可选）", "Reason (optional)"),
    "character.reason_placeholder": ("例如：剧情奖励 / 惩罚 / 测试分支", "For example: story reward / penalty / test branch"),
    "character.apply_adjustment": ("应用改值", "Apply Adjustment"),
    "character.applying": ("应用中…", "Applying…"),
    "character.state_inventory_notes": ("状态、物品与备注", "Conditions, Inventory & Notes"),
    "character.conditions_field": ("当前状态（逗号或换行分隔）", "Current Conditions (comma- or line-separated)"),
    "character.conditions_placeholder": ("例如：中毒、隐匿、疲惫", "For example: poisoned, hidden, exhausted"),
    "character.inventory_field": ("物品（逗号或换行分隔）", "Inventory (comma- or line-separated)"),
    "character.inventory_placeholder": ("例如：短剑、治疗药水、银钥匙", "For example: shortsword, healing potion, silver key"),
    "character.notes_field": ("角色备注", "Character Notes"),
    "character.notes_placeholder": ("例如：害怕深水；欠酒馆老板娘一个人情。", "For example: fears deep water; owes the innkeeper a favor."),
    "character.save_state": ("保存状态/物品", "Save Conditions / Inventory"),
    "character.saving": ("保存中…", "Saving…"),
    "character.json_summary": ("角色卡 JSON（高级）", "Character Sheet JSON (Advanced)"),
    "character.json_label": ("角色卡 JSON（权威状态建议落库，不依赖模型“记得”）", "Character sheet JSON (store authoritative state instead of relying on the model to remember it)"),
    "character.json_placeholder": ('{"name":"主角","hp":10,"gold":5,"inventory":["短剑"]}', '{"name":"Hero","hp":10,"gold":5,"inventory":["Shortsword"]}'),
    "character.save_sheet": ("保存角色卡", "Save Character Sheet"),
    "character.pending_changes": ("待确认变更", "Pending Changes"),
    "character.change.id": ("ID", "ID"),
    "character.change.type": ("类型", "Type"),
    "character.change.turn": ("回合", "Turn"),
    "character.change.kind.state_delta": ("角色状态", "Character State"),
    "character.change.kind.thread_updates": ("剧情线", "Plot Threads"),
    "character.change.preview": ("变更预览", "Change Preview"),
    "character.change.no_preview": ("（暂无可读预览，请查看原始 JSON）", "No readable preview is available; inspect the raw JSON."),
    "character.change.raw_json": ("原始 JSON", "Raw JSON"),
    "character.change.apply": ("应用", "Apply"),
    "character.change.reject": ("拒绝", "Reject"),
    "character.rejecting": ("拒绝中…", "Rejecting…"),
    "character.pending.empty": ("（暂无待确认变更）", "No pending changes."),
    "character.preview.unsupported_summary": ("剧情线更新建议", "Plot Thread Update Proposal"),
    "character.preview.unsupported_line": ("暂不支持自动应用，请到剧情线页面手动处理。", "Automatic application is not supported; handle this on the Plot Threads page."),
    "character.notice.sheet_saved": ("角色卡已保存", "Character sheet saved"),
    "character.notice.request_missing": ("未找到该变更请求（可能已处理）。", "That change request was not found; it may already have been handled."),
    "character.notice.invalid_rejected_detail": ("已拒绝：{detail}", "Rejected: {detail}"),
    "character.notice.invalid_rejected": ("变更数据无效，已拒绝。", "The change data was invalid and has been rejected."),
    "character.notice.threads_applied": ("已应用剧情线更新。", "Plot thread updates applied."),
    "character.notice.unsupported_rejected": ("已拒绝：暂不支持自动应用该类型。", "Rejected: this change type cannot be applied automatically."),
    "character.notice.change_applied": ("已应用变更。", "Change applied."),
    "character.notice.change_rejected": ("已拒绝变更。", "Change rejected."),
    "character.notice.adjustment_applied": ("已应用快速改值。", "Quick adjustment applied."),
    "character.notice.state_saved": ("已保存状态、物品与备注。", "Conditions, inventory, and notes saved."),
    "cheats.notice.saved": ("金手指设置已保存", "Cheat settings saved"),
}
