"""Home, model setup, and new-adventure messages."""

MESSAGES: dict[str, tuple[str, str]] = {
    # Home dashboard.
    "home.page.title": ("继续冒险 - one_person_dnd", "Continue Adventure - one_person_dnd"),
    "home.continue.kicker": ("继续上次旅程", "Continue your journey"),
    "home.unnamed_adventure": ("未命名冒险", "Unnamed adventure"),
    "home.story_opening": ("故事开场", "Story opening"),
    "home.last_played": ("最近游玩 · {value}", "Last played · {value}"),
    "home.current_scene": ("当前场景", "Current scene"),
    "home.no_opening_scene": ("尚未写下开场地点", "No opening location yet"),
    "home.story_stopped": ("故事停在这里", "Where the story paused"),
    "home.no_story": (
        "这场冒险还没有故事记录。进入后写下第一个行动，DM 会从这里接住你。",
        "This adventure has no story yet. Enter it and write your first action; the DM will pick it up from there.",
    ),
    "home.continue_adventure": ("继续这场冒险", "Continue this adventure"),
    "home.create_new": ("创建新冒险", "Create a new adventure"),
    "home.view_all": ("查看全部冒险", "View all adventures"),
    "home.journey_status": ("旅途状态", "Journey status"),
    "home.journey_mark": ("旅", "A"),
    "home.unnamed_character": ("未命名角色", "Unnamed character"),
    "home.ancestry_unknown": ("种族未定", "Ancestry undecided"),
    "home.hp": ("生命", "HP"),
    "home.gold": ("金币", "Gold"),
    "home.status": ("状态", "Status"),
    "home.stable": ("状态稳定", "Stable"),
    "home.current_goal": ("当前目标", "Current goal"),
    "home.no_character": (
        "还没有角色资料。进入冒险面板后可以随时补充。",
        "There is no character information yet. You can add it anytime from the adventure panel.",
    ),
    "home.dm_ready": ("DM 已就绪", "DM ready"),
    "home.dm_not_connected": ("DM 尚未连接", "DM not connected"),
    "home.can_continue": ("可以继续行动", "Ready for your next action"),
    "home.select_model_first": ("先选择一个模型再开始", "Choose a model before you begin"),
    "home.adjust_model": ("调整", "Adjust"),
    "home.configure_model": ("去配置模型", "Configure a model"),
    "onboarding.inline_separator": ("、", ", "),

    # Model management.
    "models.page.title": ("DM 模型 - one_person_dnd", "DM Models - one_person_dnd"),
    "models.eyebrow": ("DM 的连接方式", "Connect your DM"),
    "models.heading": ("模型", "Models"),
    "models.back_to_play": ("回到游玩", "Back to play"),
    "models.created.title": (
        "模型配置已保存，建议先测试连接",
        "Model settings saved — test the connection next",
    ),
    "models.created.body": (
        "保存成功不代表模型服务已经连通。确认测试成功后，再创建新冒险；模型配置仍可在下方继续管理。",
        "Saving does not confirm that the model is reachable. Test it before creating a new adventure; you can keep managing models below.",
    ),
    "models.test_connection_cta": ("去测试连接", "Test the connection"),
    "models.create_new_adventure": ("创建新冒险", "Create a new adventure"),
    "models.existing.title": ("已有模型", "Saved models"),
    "models.existing.body": (
        "当前模型会负责生成叙事、行动建议和世界内容。",
        "The active model generates narration, action suggestions, and world content.",
    ),
    "models.current_dm": ("当前 DM", "Current DM"),
    "models.use_for_dm": ("用于当前 DM", "Use for current DM"),
    "models.test_connection": ("测试连接", "Test connection"),
    "models.testing": ("测试中……", "Testing…"),
    "models.edit_summary": ("编辑与技术信息", "Edit and technical details"),
    "models.field.display_name": ("显示名称", "Display name"),
    "models.field.provider": ("服务类型（Provider）", "Service type (Provider)"),
    "models.field.base_url": ("接口地址（Base URL）", "Endpoint (Base URL)"),
    "models.field.model": ("模型标识（Model）", "Model identifier (Model)"),
    "models.field.api_key_keep": (
        "访问密钥（留空则保持原值）",
        "API key (leave blank to keep the current value)",
    ),
    "models.field.timeout": ("响应等待上限（秒）", "Response timeout (seconds)"),
    "models.placeholder.api_key_keep": ("留空则保持原密钥", "Leave blank to keep the current key"),
    "models.save_changes": ("保存修改", "Save changes"),
    "models.delete_confirm": (
        "确认删除“{name}”吗？此操作不会删除冒险存档。",
        "Delete “{name}”? This will not delete any adventure saves.",
    ),
    "models.delete": ("删除这个模型", "Delete this model"),
    "models.config_id": ("配置编号：{id}", "Configuration ID: {id}"),
    "models.empty.title": ("还没有可用模型。", "No models are available yet."),
    "models.empty.body": (
        "展开下方“添加模型”，最快可以从 DeepSeek 开始。",
        "Open “Add model” below; DeepSeek is the quickest place to start.",
    ),
    "models.add.summary": ("添加模型", "Add model"),
    "models.quickstart.title": ("DeepSeek 快速开始", "DeepSeek quick start"),
    "models.quickstart.body": (
        "只需填写访问密钥，其他连接参数已经准备好。",
        "Enter an API key; the other connection settings are ready.",
    ),
    "models.quickstart.recommended": ("推荐入门", "Recommended"),
    "models.field.api_key": ("访问密钥", "API key"),
    "models.save_deepseek": ("保存 DeepSeek", "Save DeepSeek"),
    "models.custom.summary": ("连接其他兼容服务", "Connect another compatible service"),
    "models.placeholder.custom_name": ("例如：本地模型", "For example: Local model"),
    "models.field.base_url_v1": (
        "接口地址（Base URL，通常以 /v1 结尾）",
        "Endpoint (Base URL, usually ending in /v1)",
    ),
    "models.placeholder.model": ("例如：gpt-4o-mini / llama3", "For example: gpt-4o-mini / llama3"),
    "models.field.api_key_optional": ("访问密钥（可留空）", "API key (optional)"),
    "models.placeholder.api_key_optional": (
        "本地服务通常可留空",
        "Usually optional for local services",
    ),
    "models.save_custom": ("保存自定义模型", "Save custom model"),
    "models.provider.openai_compat": (
        "自定义 OpenAI 兼容服务",
        "Custom OpenAI-compatible service",
    ),
    "models.provider.deepseek": ("DeepSeek", "DeepSeek"),
    "models.test.success": ("连接成功：{message}", "Connection successful: {message}"),
    "models.test.failure": ("连接失败：{message}", "Connection failed: {message}"),
    "models.error.profile_not_found": ("未找到该模型配置", "That model configuration was not found"),
    "models.setup.page_title": (
        "模型配置已迁移 - one_person_dnd",
        "Model Settings Moved - one_person_dnd",
    ),
    "models.setup.title": (
        "模型配置已经合并到“模型”页面",
        "Model settings now live on the Models page",
    ),
    "models.setup.body": (
        "现在可以在同一处查看、测试、启用和编辑所有模型。",
        "You can now view, test, activate, and edit every model in one place.",
    ),
    "models.setup.cta": ("前往模型页面", "Go to Models"),

    # New-adventure form and route-owned public errors.
    "new.page.title": ("创建新冒险 - one_person_dnd", "Create a New Adventure - one_person_dnd"),
    "new.eyebrow": ("从一张空白地图开始", "Start with a blank map"),
    "new.heading": ("创建新冒险", "Create a new adventure"),
    "new.lede": (
        "说出你想玩的故事，或让模型先给你一套可修改的灵感。确认前不会改动现有冒险。",
        "Describe the story you want, or ask the model for an editable idea. Nothing changes until you confirm.",
    ),
    "new.model_not_ready.title": ("模型尚未就绪", "The model is not ready"),
    "new.model_not_ready.body": (
        "先选择一个可用模型，回来后再生成冒险。",
        "Choose an available model, then return to generate your adventure.",
    ),
    "new.model_not_ready.cta": ("去配置模型", "Configure a model"),
    "new.failure.title": ("这次没有生成成功", "Generation did not succeed"),
    "new.idea.title": ("你的冒险构想", "Your adventure idea"),
    "new.brief.label": ("先说说你想玩什么", "What would you like to play?"),
    "new.brief.placeholder": (
        "例如：我想扮演一名失去记忆的守灯人，在被潮汐吞没的群岛追查一艘幽灵船……",
        "For example: I want to play an amnesiac lighthouse keeper tracking a ghost ship through islands swallowed by the tides…",
    ),
    "new.proposal.eyebrow": ("模型给出的可编辑提案", "Editable model proposal"),
    "new.proposal.title": (
        "在生成完整设定前，再改一次方向",
        "Refine the direction before generating the full adventure",
    ),
    "new.field.adventure_name": ("冒险名称", "Adventure name"),
    "new.field.chapter_title": ("第一章标题", "First chapter title"),
    "new.preferences.summary": ("调整故事偏好", "Adjust story preferences"),
    "new.field.genre": ("故事风格", "Genre"),
    "new.field.tone": ("故事基调", "Tone"),
    "new.field.tech_level": ("时代与科技", "Era and technology"),
    "new.field.themes": ("想探索的主题", "Themes to explore"),
    "new.field.character_count": ("队伍角色数量", "Party size"),
    "new.field.constraints": ("必须遵守的设定", "Required constraints"),
    "new.constraints.placeholder": (
        "例如：世界里不能复活；主角必须是半精灵游侠；开局在雪国小镇……",
        "For example: resurrection is impossible; the hero must be a half-elf ranger; begin in a snowy town…",
    ),
    "new.action.generate": ("生成完整冒险", "Generate full adventure"),
    "new.action.generating": ("正在铺开世界……", "Building the world…"),
    "new.action.propose": ("帮我想一套", "Suggest an adventure"),
    "new.action.proposing": ("正在构思……", "Thinking…"),
    "new.action.waiting": ("模型正在构思，请稍候……", "The model is thinking. Please wait…"),
    "new.assurance.aria": ("创建说明", "Creation details"),
    "new.assurance.title": ("一份独立的新存档", "A separate new save"),
    "new.assurance.body": (
        "模型会先生成世界设定、角色与开场。你确认采用后，系统才会创建一个新的冒险和第一章。",
        "The model first generates the world, characters, and opening. A new adventure and first chapter are created only after you confirm.",
    ),
    "new.assurance.existing_unchanged": ("现有冒险保持原样", "Existing adventures stay unchanged"),
    "new.assurance.preview_first": (
        "生成结果先以易读方式预览",
        "Review the generated result in a readable format first",
    ),
    "new.assurance.names_editable": (
        "名称和第一章标题可再次修改",
        "You can edit the adventure and chapter names again",
    ),
    "new.defaults.genre": ("奇幻", "Fantasy"),
    "new.defaults.tone": ("冒险", "Adventure"),
    "new.defaults.tech_level": ("中世纪", "Medieval"),
    "new.defaults.themes": ("探索,谜团", "Exploration, mystery"),
    "new.error.model_not_configured": (
        "模型尚未配置，请先在“模型”页面选择或创建可用配置。",
        "No model is configured. Choose or create one on the Models page first.",
    ),
    "new.error.json_root": ("JSON 根必须是对象", "The JSON root must be an object"),
    "new.error.source_form": (
        "返回修改所需的原始表单格式不正确",
        "The saved form data needed to return to editing is invalid",
    ),
    "new.error.generated_shape": (
        "生成结果中的世界设定或角色卡格式不正确",
        "The generated world or character sheet has an invalid format",
    ),
    "new.error.invalid_generated_result": (
        "生成结果格式不正确",
        "The generated result has an invalid format",
    ),
    "new.error.character_rules_invalid": (
        "生成结果中的角色规则数据不正确",
        "The generated character rules data is invalid",
    ),
    "new.error.restore_draft": (
        "无法恢复刚才的创建草稿：{detail}",
        "Could not restore the adventure draft: {detail}",
    ),
    "new.error.apply_preview": (
        "无法采用这份冒险预览：{detail}",
        "Could not apply this adventure preview: {detail}",
    ),
    "new.error.preview_missing_content": (
        "冒险预览缺少有效的世界设定或角色卡",
        "The adventure preview is missing a valid world or character sheet",
    ),
    "new.error.apply_character": (
        "无法采用这份角色卡：{detail}",
        "Could not apply this character sheet: {detail}",
    ),

    # New-adventure preview.
    "new.preview.page.title": ("采用前预览 - one_person_dnd", "Preview Before Applying - one_person_dnd"),
    "new.preview.eyebrow": ("采用前预览", "Preview before applying"),
    "new.preview.lede": (
        "这会创建一份独立的新冒险。原有存档不会被覆盖。",
        "This creates a separate new adventure. Existing saves will not be overwritten.",
    ),
    "new.preview.confirm_names": ("最后确认名称", "Confirm the names"),
    "new.preview.summary_aria": ("生成结果概览", "Generated adventure summary"),
    "new.preview.world_settings": ("世界设定", "World entries"),
    "new.preview.world_count.one": ("{count} 条", "{count} entry"),
    "new.preview.world_count.other": ("{count} 条", "{count} entries"),
    "new.preview.companions": ("角色", "Characters"),
    "new.preview.companion_count.one": ("{count} 名角色", "{count} character"),
    "new.preview.companion_count.other": ("{count} 名角色", "{count} characters"),
    "new.preview.opening": ("开场地点或局面", "Opening location or situation"),
    "new.preview.story_opening": ("故事开场", "Story opening"),
    "new.preview.world_heading": ("这个世界", "This world"),
    "new.preview.type.rule": ("规则", "Rule"),
    "new.preview.type.location": ("地点", "Location"),
    "new.preview.type.npc": ("人物", "Character"),
    "new.preview.type.organization": ("势力", "Organization"),
    "new.preview.type.setting": ("设定", "World detail"),
    "new.preview.empty_world": (
        "没有生成世界设定。你可以返回修改后重试。",
        "No world entries were generated. Return to edit and try again.",
    ),
    "new.preview.companions_heading": ("你的队伍", "Your party"),
    "new.preview.unnamed_character": ("未命名角色", "Unnamed character"),
    "new.preview.character_line": (
        "等级 {level} · {race} · {role}",
        "Level {level} · {race} · {role}",
    ),
    "new.preview.race_unknown": ("种族未定", "Ancestry undecided"),
    "new.preview.role_unknown": ("职业未定", "Class undecided"),
    "new.preview.goal": ("目标：", "Goal: "),
    "new.preview.hp": ("生命 {value}", "HP {value}"),
    "new.preview.gold": ("金币 {value}", "Gold {value}"),
    "new.preview.skills": ("熟练技能：{value}", "Proficient skills: {value}"),
    "new.preview.inventory": ("随身物品：{value}", "Inventory: {value}"),
    "new.preview.empty_companions": (
        "没有生成角色。你可以返回修改后重试。",
        "No characters were generated. Return to edit and try again.",
    ),
    "new.preview.opening_note": ("开场提示", "Opening note"),
    "new.preview.technical": ("查看技术数据", "View technical data"),
    "new.preview.create_and_start": ("创建这场冒险并开始", "Create this adventure and begin"),
    "new.preview.return_to_edit": ("返回修改", "Return to edit"),
}
